
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmgmbpuwlijelqszgxby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZ21icHV3bGlqZWxxc3pneGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTI4MjQsImV4cCI6MjA1NTA4ODgyNH0._uXaa0_4UXOUXsxul14DUEPWjVmQM5kfZThIHMLLLSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  db: {
    schema: 'public',
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Helper function to create unique channel names
export const getChannelName = (tableName: string, suffix = '') => {
  const randomId = Math.random().toString(36).substring(2, 10);
  return `${tableName}-updates-${randomId}${suffix ? `-${suffix}` : ''}`;
};

// Debug initialization
console.log("Supabase client initialized with URL:", SUPABASE_URL);
